global:
    scrape_interval: 10s
    evaluation_interval: 10s
    scrape_timeout: 10s
    external_labels:
        monitor: 'astro-dev'
scrape_configs:
  - job_name: 'airflow-statsd-exporter'
    static_configs:
      - targets: ['statsd:9102']
