{
 "title": "Airflow Statsd Metrics Big List",
 "description": "Most Airflow statsd metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Scheduler Critical Section Duration (ms)",
   "type": "timeseries",
   "description": "Milliseconds spent in the critical section of scheduler loop – only a single scheduler can enter this loop at a time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=\"airflow_scheduler_critical_section_duration\", __name__!~\"airflow_scheduler_critical_section_duration_.+_sum\", __name__!~\"airflow_scheduler_critical_section_duration_.+_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Run First Task Scheduling Delay (s)",
   "type": "timeseries",
   "description": "Seconds elapsed between first task start_date and dagrun expected start",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_dagrun_.+?_first_task_scheduling_delay\", __name__!~\"airflow_dagrun_.+?_first_task_scheduling_delay.+_sum\", __name__!~\"airflow_dagrun_.+?_first_task_scheduling_delay.+_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler Critical Section Busy (2m)",
   "type": "timeseries",
   "description": "Count of times a scheduler process tried to get a lock on the critical section (needed to send tasks to the executor) and found it locked by another process.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_scheduler_critical_section_busy\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Run Schedule Delay (s)",
   "type": "timeseries",
   "description": "Seconds of delay between the scheduled DagRun start date and the actual DagRun start date",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_dagrun_schedule_delay_.+?\", __name__!~\"airflow_dagrun_schedule_delay_.+_sum\", __name__!~\"airflow_dagrun_schedule_delay_.+_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful DAG Run Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_dagrun_duration_success_.+\", __name__!~\"airflow_dagrun_duration_success_.+_count\", __name__!~\"airflow_dagrun_duration_success_.+_sum\", quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed DAG Run Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_dagrun_duration_failed_.+\", __name__!~\"airflow_dagrun_duration_failed_.+_count\", __name__!~\"airflow_dagrun_duration_failed_.+_sum\", quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Dependency Check (ms)",
   "type": "timeseries",
   "description": "Milliseconds taken to check DAG dependencies",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_dagrun_dependency_check_.+\", __name__!~\"airflow_dagrun_dependency_check_.+_count\", __name__!~\"airflow_dagrun_dependency_check_.+_sum\", quantile=\"0.99\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Default Pool - Open, Running, Queued, Starving; Triggers Running",
   "type": "timeseries",
   "description": "https://airflow.apache.org/docs/apache-airflow/stable/logging-monitoring/metrics.html",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_pool_.+\"}\r\n",
     "legendFormat": "__auto"
    },
    { "expr": "airflow_triggers_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Executor Open Slots, Queued Tasks, Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_executor_.+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Airflow Scheduler Tasks Running, Starving, Executable, Killed Externally",
   "type": "timeseries",
   "description": "Number of tasks running in executor\nNumber of tasks that cannot be scheduled because of no open slot in pool\nNumber of tasks that are ready for execution (set to queued) with respect to pool limits, dag concurrency, executor state, and priority.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_scheduler_tasks_.+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Processing Last Run Seconds Ago (s)",
   "type": "timeseries",
   "description": "Seconds since <dag_file> was last processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_dag_processing_last_run_seconds_ago_.+\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Processing Total Parse Time (s)",
   "type": "timeseries",
   "description": "Seconds taken to scan and import all DAG files once",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "airflow_dag_processing_total_parse_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Processing Import Errors",
   "type": "timeseries",
   "description": "Number of errors from trying to parse DAG files",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Bag Size",
   "type": "timeseries",
   "description": "Number of DAGs found when the scheduler ran a scan based on it’s configuration",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "airflow_dagbag_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Triggers Blocked Main Thread (2m)",
   "type": "timeseries",
   "description": "Number of triggers that blocked the main thread (likely due to not being fully asynchronous)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_triggers_blocked_main_thread\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Instances Created (2m)",
   "type": "timeseries",
   "description": "Number of tasks instances created for a given Operator",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_task_instance_created_.+\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Celery Execute Command Failure (2m)",
   "type": "timeseries",
   "description": "Number of non-zero exit code from Celery task.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_celery_execute_command_failure\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Celery Task Timeout Errors (2m)",
   "type": "timeseries",
   "description": "Number of AirflowTaskTimeout errors raised when publishing Task to Celery Broker.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_celery_task_timeout_error\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orphaned Tasks Adopted, Cleared",
   "type": "timeseries",
   "description": "Number of Orphaned tasks [adopted, cleared] by the Scheduler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_scheduler_orphaned_tasks_adopted\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(label_replace({__name__=~\"airflow_scheduler_orphaned_tasks_cleared\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Killed Externally",
   "type": "timeseries",
   "description": "Number of tasks killed externally",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_scheduler_tasks_killed_externally\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Processing Manager Stalls",
   "type": "timeseries",
   "description": "Number of stalled DagFileProcessorManager",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_dag_processing_manager_stalls\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Processor Timeouts",
   "type": "timeseries",
   "description": "Number of file processors that have been killed due to taking too long",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_dag_file_processor_timeouts\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(label_replace({__name__=~\"airflow_dag_processing_processor_timeouts\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG parsing processes (5m rate)",
   "type": "timeseries",
   "description": "Number of currently running DAG parsing processes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_dag_processing_processes\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[5m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduler Heartbeat (2m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_scheduler_heartbeat\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zombies Killed (2m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_zombies_killed\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Airflow Task Instance Successes (2m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_ti_successes\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Airflow Task Instance Failures (2m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_ti_failures\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Airflow Operator Successes (2 min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_operator_successes_.+\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Airflow Operator Failures (2 min)",
   "type": "timeseries",
   "description": "airflow_operator_failures_.+",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"airflow_operator_failures_.+\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[2m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pool_running_slots_default_pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 108 },
   "targets": [
    {
     "expr": "airflow_pool_running_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "first_task_scheduling_delay (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_dagrun_.+?_first_task_scheduling_delay\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pool_queued_slots_default_pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "airflow_pool_queued_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}