{
 "title": "JM Astro Scaling Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "pool_running_slots_default_pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "airflow_pool_running_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "first_task_scheduling_delay (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_dagrun_.+_first_task_scheduling_delay\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pool_queued_slots_default_pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "airflow_pool_queued_slots_default_pool",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DAG Run Schedule Delay (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{__name__=~\"airflow_dagrun_schedule_delay_.+?\", __name__!~\"airflow_dagrun_schedule_delay_.+_sum\", __name__!~\"airflow_dagrun_schedule_delay_.+_count\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}